//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmplaWeb.Security.AmplaSecurity2007 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06", ConfigurationName="AmplaSecurity2007.ISecurityWebService")]
    public interface ISecurityWebService {
        
        // CODEGEN: Generating message contract since the operation CreateSession is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.citect.com/Ampla/Security/2007/06:createSessionIn", ReplyAction="http://www.citect.com/Ampla/Security/2007/06/ISecurityWebService/CreateSessionRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AmplaWeb.Security.AmplaSecurity2007.CreateSessionResponse1 CreateSession(AmplaWeb.Security.AmplaSecurity2007.CreateSessionRequest1 request);
        
        // CODEGEN: Generating message contract since the operation RenewSession is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.citect.com/Ampla/Security/2007/06:renewSessionIn", ReplyAction="http://www.citect.com/Ampla/Security/2007/06/ISecurityWebService/RenewSessionResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AmplaWeb.Security.AmplaSecurity2007.RenewSessionResponse1 RenewSession(AmplaWeb.Security.AmplaSecurity2007.RenewSessionRequest1 request);
        
        // CODEGEN: Generating message contract since the operation ReleaseSession is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.citect.com/Ampla/Security/2007/06:releaseSessionIn", ReplyAction="http://www.citect.com/Ampla/Security/2007/06/ISecurityWebService/ReleaseSessionRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionResponse1 ReleaseSession(AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06")]
    public partial class CreateSessionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06")]
    public partial class ReleaseSessionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06")]
    public partial class ReleaseSessionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Session sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Session Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("Session");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06")]
    public partial class Session : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06")]
    public partial class RenewSessionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Session sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Session Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("Session");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06")]
    public partial class RenewSessionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Session sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Session Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("Session");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06")]
    public partial class CreateSessionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Session sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Session Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
                this.RaisePropertyChanged("Session");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSessionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06", Order=0)]
        public AmplaWeb.Security.AmplaSecurity2007.CreateSessionRequest CreateSessionRequest;
        
        public CreateSessionRequest1() {
        }
        
        public CreateSessionRequest1(AmplaWeb.Security.AmplaSecurity2007.CreateSessionRequest CreateSessionRequest) {
            this.CreateSessionRequest = CreateSessionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSessionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06", Order=0)]
        public AmplaWeb.Security.AmplaSecurity2007.CreateSessionResponse CreateSessionResponse;
        
        public CreateSessionResponse1() {
        }
        
        public CreateSessionResponse1(AmplaWeb.Security.AmplaSecurity2007.CreateSessionResponse CreateSessionResponse) {
            this.CreateSessionResponse = CreateSessionResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenewSessionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06", Order=0)]
        public AmplaWeb.Security.AmplaSecurity2007.RenewSessionRequest RenewSessionRequest;
        
        public RenewSessionRequest1() {
        }
        
        public RenewSessionRequest1(AmplaWeb.Security.AmplaSecurity2007.RenewSessionRequest RenewSessionRequest) {
            this.RenewSessionRequest = RenewSessionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenewSessionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06", Order=0)]
        public AmplaWeb.Security.AmplaSecurity2007.RenewSessionResponse RenewSessionResponse;
        
        public RenewSessionResponse1() {
        }
        
        public RenewSessionResponse1(AmplaWeb.Security.AmplaSecurity2007.RenewSessionResponse RenewSessionResponse) {
            this.RenewSessionResponse = RenewSessionResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReleaseSessionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06", Order=0)]
        public AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionRequest ReleaseSessionRequest;
        
        public ReleaseSessionRequest1() {
        }
        
        public ReleaseSessionRequest1(AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionRequest ReleaseSessionRequest) {
            this.ReleaseSessionRequest = ReleaseSessionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReleaseSessionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.citect.com/Ampla/Security/2007/06", Order=0)]
        public AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionResponse ReleaseSessionResponse;
        
        public ReleaseSessionResponse1() {
        }
        
        public ReleaseSessionResponse1(AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionResponse ReleaseSessionResponse) {
            this.ReleaseSessionResponse = ReleaseSessionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityWebServiceChannel : AmplaWeb.Security.AmplaSecurity2007.ISecurityWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityWebServiceClient : System.ServiceModel.ClientBase<AmplaWeb.Security.AmplaSecurity2007.ISecurityWebService>, AmplaWeb.Security.AmplaSecurity2007.ISecurityWebService {
        
        public SecurityWebServiceClient() {
        }
        
        public SecurityWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmplaWeb.Security.AmplaSecurity2007.CreateSessionResponse1 AmplaWeb.Security.AmplaSecurity2007.ISecurityWebService.CreateSession(AmplaWeb.Security.AmplaSecurity2007.CreateSessionRequest1 request) {
            return base.Channel.CreateSession(request);
        }
        
        public AmplaWeb.Security.AmplaSecurity2007.CreateSessionResponse CreateSession(AmplaWeb.Security.AmplaSecurity2007.CreateSessionRequest CreateSessionRequest) {
            AmplaWeb.Security.AmplaSecurity2007.CreateSessionRequest1 inValue = new AmplaWeb.Security.AmplaSecurity2007.CreateSessionRequest1();
            inValue.CreateSessionRequest = CreateSessionRequest;
            AmplaWeb.Security.AmplaSecurity2007.CreateSessionResponse1 retVal = ((AmplaWeb.Security.AmplaSecurity2007.ISecurityWebService)(this)).CreateSession(inValue);
            return retVal.CreateSessionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmplaWeb.Security.AmplaSecurity2007.RenewSessionResponse1 AmplaWeb.Security.AmplaSecurity2007.ISecurityWebService.RenewSession(AmplaWeb.Security.AmplaSecurity2007.RenewSessionRequest1 request) {
            return base.Channel.RenewSession(request);
        }
        
        public AmplaWeb.Security.AmplaSecurity2007.RenewSessionResponse RenewSession(AmplaWeb.Security.AmplaSecurity2007.RenewSessionRequest RenewSessionRequest) {
            AmplaWeb.Security.AmplaSecurity2007.RenewSessionRequest1 inValue = new AmplaWeb.Security.AmplaSecurity2007.RenewSessionRequest1();
            inValue.RenewSessionRequest = RenewSessionRequest;
            AmplaWeb.Security.AmplaSecurity2007.RenewSessionResponse1 retVal = ((AmplaWeb.Security.AmplaSecurity2007.ISecurityWebService)(this)).RenewSession(inValue);
            return retVal.RenewSessionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionResponse1 AmplaWeb.Security.AmplaSecurity2007.ISecurityWebService.ReleaseSession(AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionRequest1 request) {
            return base.Channel.ReleaseSession(request);
        }
        
        public AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionResponse ReleaseSession(AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionRequest ReleaseSessionRequest) {
            AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionRequest1 inValue = new AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionRequest1();
            inValue.ReleaseSessionRequest = ReleaseSessionRequest;
            AmplaWeb.Security.AmplaSecurity2007.ReleaseSessionResponse1 retVal = ((AmplaWeb.Security.AmplaSecurity2007.ISecurityWebService)(this)).ReleaseSession(inValue);
            return retVal.ReleaseSessionResponse;
        }
    }
}
